### 1. Import numpy as np and see the version

In [2]:
import numpy as np
print(np.__version__)

1.19.2


### 2. How to create a 1D array in given Range?

In [4]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 3. How to create a boolean array?

In [5]:
np.full((3, 3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### 4. How to extract items that satisfy a given condition from 1D array?


In [6]:
b=a[a%2==1]
print(b)
print(a)

[1 3 5 7 9]
[0 1 2 3 4 5 6 7 8 9]


### 5. How to replace items that satisfy a condition with another value in numpy array?


In [7]:
a[a%2==1] = -1
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### 6. How to replace items that satisfy a condition without affecting the original array?

In [8]:
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)        #.where(condition, if true statement, else statement)
print(arr)
print(out)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


### 7. How to reshape an array?


In [13]:
print(np.reshape(arr, (2,5)))

#OR we can alternatively do this..

print(a.reshape(5,2))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 0 -1]
 [ 2 -1]
 [ 4 -1]
 [ 6 -1]
 [ 8 -1]]


### 8. How to stack two arrays vertically?


In [35]:
vrr=np.ones((2,10),dtype='int32')
np.vstack((arr,brr))                         #notice that vstack() takes only one arg! which is the tuple of arrays! 

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

### 9. How to stack two arrays horizontally?


In [52]:
hrr=np.ones((10,),dtype='int32')
np.hstack((arr,hrr))                         #notice that hstack() takes only one arg! which is the tuple of arrays! 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


### 10. How to generate custom sequences in numpy without hardcoding?


In [50]:
a = np.array([1,2,3])
np.r_[np.repeat(a,3),np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

### 11. How to get the common items between two python numpy arrays?


In [61]:
arr1 = np.array([1,2,3,2,3,4,3,4,5,6])
arr2 = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(arr1,arr2))

# In case you want to intersect more than two arrays:

from functools import reduce
reduce(np.intersect1d, ([1, 3, 4, 3], [3, 1, 2, 1], [6, 3, 4, 2]))

[2 4]


array([3])

### 12. How to remove from one array those items that exist in another?


In [67]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.setdiff1d(a,b)

array([1, 2, 3, 4])

### 13. How to get the positions where elements of two arrays match?


In [68]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

### 14. How to extract all numbers between a given range from a numpy array?



In [82]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
print(a[((a>=6) & (a<=10))])

[ 6  9 10]


### 15. How to make a python function that handles scalars to work on numpy arrays?


In [86]:
def find_max_of(a,b):
    if a>b:
        return a
    else:
        return b
    
best_of_two= np.vectorize(find_max_of)


a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
best_of_two(a, b)

array([6, 7, 9, 8, 9, 7, 5])